initialize package
Developer-DAO/community pull request #20
Opened 2021-09-30 13:14 UTC by with-heart

This PR initializes this project as a package. It also adds `husky`, `lint-staged`, and `prettier`, so we can have that sweet sweet `prettier` formatting on commit.

2021-09-30 13:42 UTC, codingwithmanny commented on .gitignore
> +.DS_Store
```suggestion
.DS_Store
*.log
package-lock.json
```

2021-09-30 13:42 UTC, codingwithmanny commented on .husky/pre-commit
> +npx lint-staged
```suggestion
./node_modules/.bin/line-staged
```

2021-09-30 13:43 UTC, codingwithmanny requested changes
Let me know what you think about the changes.

2021-09-30 13:47 UTC, Dhaiwat10 commented
Might be kinda off-topic so pardon me but I'd love to know the purpose behind making this a package 😄 Are gonna use this to serve data, or something else?

2021-09-30 16:22 UTC, with-heart commented
> I think it's just to format the .md files.

Yeap that's literally it

2021-09-30 22:53 UTC, with-heart commented
Probably some other things. But yeah that's it for now 😉

2021-10-02 10:08 UTC, codingwithmanny requested changes
Ignore...

2021-10-02 10:08 UTC, codingwithmanny commented on package.json
> +    "*.{json,md}": "prettier --write"
```suggestion
    "*.{json,md}": "prettier --write *.md"
```

2021-10-02 10:20 UTC, codingwithmanny approved these changes
LGTM

2021-11-16 02:17 UTC, merged